"""added field  unique for sesion

Revision ID: 62d28d9f2645
Revises: e8ad0702401a
Create Date: 2026-04-24 16:21:34.620326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d28d9f2645'
down_revision: Union[str, Sequence[str], None] = 'e8ad0702401a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_shares', sa.Column('granted_by', sa.Integer(), nullable=True))
    op.add_column('event_shares', sa.Column('access_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_event_shares_event_user', 'event_shares', ['event_id', 'user_id'])
    op.create_foreign_key(None, 'event_shares', 'users', ['granted_by'], ['id'])
    op.create_index(op.f('ix_sessions_session_code'), 'sessions', ['session_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_session_code'), table_name='sessions')
    op.drop_constraint(None, 'event_shares', type_='foreignkey')
    op.drop_constraint('uq_event_shares_event_user', 'event_shares', type_='unique')
    op.drop_column('event_shares', 'access_date')
    op.drop_column('event_shares', 'granted_by')
    # ### end Alembic commands ###
