"""added delete to inventory trnasaction

Revision ID: a9070fe8fc39
Revises: 62d28d9f2645
Create Date: 2026-05-01 17:43:53.456373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9070fe8fc39'
down_revision: Union[str, Sequence[str], None] = '62d28d9f2645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_transactions', 'deleted')
    # ### end Alembic commands ###
